pipeline {
    agent any

    stages {
        stage('Get approval') {
            options {
                timeout(time: 59, unit: 'MINUTES')
            }
            steps {
                input "Please Approve To Proceed The Deployment"
            }
        }

        stage('Checkout Latest Code') {
            steps {
                dir('tg-test-cicd') {
                    git branch: 'staging',
                        credentialsId: '5bb806d0-f7ec-44bb-bcf9-6194de97138e',
                        url: 'https://github.com/tgrid-usa/test-cicd.git'
                    sh 'ls -la'
                }
            }
        }

        stage('Checkout Docker File') {
            steps {
                git branch: 'staging',
                    credentialsId: '5bb806d0-f7ec-44bb-bcf9-6194de97138e',
                    url: 'https://github.com/tgrid-usa/staging-dockerfile.git'
                sh 'ls -la'
                sh 'cp test-cicd/Dockerfile ./Dockerfile'
                sh 'cat Dockerfile'
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }

        stage('List Images in GCP Artifact Registry') {
            steps {
                withCredentials([file(credentialsId: 'gcp-staging', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
                    script {
                        sh "gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}"
                        sh "gcloud auth configure-docker asia-south1-docker.pkg.dev"
                        echo "Listing images in Google Artifact Registry:"
                        sh "gcloud container images list-tags asia-south1-docker.pkg.dev/tg-uat-446010/trustgrid/test-cicd --format=json"
                    }
                }
            }
        }
    }
}
