pipeline {
    agent any

    stages {
        stage('Get approval') {
            options {
                timeout(time: 59, unit: 'MINUTES')
            }
            steps {
                input "Please Approve To Proceed The Deployment"
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'staging',
                    credentialsId: '5bb806d0-f7ec-44bb-bcf9-6194de97138e',
                    url: 'https://github.com/tgrid-usa/test-cicd.git'
                    sh 'ls -la'
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Building...'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}
